# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "twke"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joseph Ruscio", "Mike Heffner"]
  s.date = "2013-10-18"
  s.description = "The ambuquad that has your back."
  s.email = "joe@ruscio.org"
  s.executables = ["twke"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/twke",
    "contrib/respawn_twke.sh",
    "dot.rvmrc",
    "lib/twke.rb",
    "lib/twke/conf.rb",
    "lib/twke/job.rb",
    "lib/twke/job_manager.rb",
    "lib/twke/plugin.rb",
    "lib/twke/plugin_manager.rb",
    "lib/twke/routes.rb",
    "plugins/admin.rb",
    "plugins/config.rb",
    "plugins/github.rb",
    "plugins/jenkins.rb",
    "plugins/jobs.rb",
    "plugins/lolcats.rb",
    "plugins/papertrail.rb",
    "plugins/pugme.rb",
    "plugins/rollout.rb",
    "plugins/ronswanson.rb",
    "plugins/run.rb",
    "plugins/snow.rb",
    "plugins/squirrel.rb",
    "plugins/twiki.rb",
    "test/helper.rb",
    "test/test_conf.rb",
    "twke.gemspec"
  ]
  s.homepage = "http://github.com/josephruscio/twke"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Bidi-Bidi-Bidi!"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, ["= 1.3.3"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<faraday>, ["~> 0.7.5"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.5.0"])
      s.add_runtime_dependency(%q<eventmachine>, ["~> 1.0.3"])
      s.add_runtime_dependency(%q<scamp>, [">= 0"])
      s.add_runtime_dependency(%q<can-has-lolcat>, [">= 0"])
      s.add_runtime_dependency(%q<papertrail-cli>, ["~> 0.8.5"])
      s.add_runtime_dependency(%q<hpricot>, ["~> 0.8.5"])
      s.add_runtime_dependency(%q<redis>, ["~> 2.2.2"])
      s.add_runtime_dependency(%q<hiredis>, ["~> 0.4.5"])
      s.add_runtime_dependency(%q<em-synchrony>, [">= 0"])
      s.add_runtime_dependency(%q<rollout>, ["~> 2.0.0"])
      s.add_runtime_dependency(%q<rollout-zk>, ["~> 1.0.1"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<pry>, ["~> 0.9.9.4"])
    else
      s.add_dependency(%q<rack>, ["= 1.3.3"])
      s.add_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_dependency(%q<faraday>, ["~> 0.7.5"])
      s.add_dependency(%q<nokogiri>, ["~> 1.5.0"])
      s.add_dependency(%q<eventmachine>, ["~> 1.0.3"])
      s.add_dependency(%q<scamp>, [">= 0"])
      s.add_dependency(%q<can-has-lolcat>, [">= 0"])
      s.add_dependency(%q<papertrail-cli>, ["~> 0.8.5"])
      s.add_dependency(%q<hpricot>, ["~> 0.8.5"])
      s.add_dependency(%q<redis>, ["~> 2.2.2"])
      s.add_dependency(%q<hiredis>, ["~> 0.4.5"])
      s.add_dependency(%q<em-synchrony>, [">= 0"])
      s.add_dependency(%q<rollout>, ["~> 2.0.0"])
      s.add_dependency(%q<rollout-zk>, ["~> 1.0.1"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<pry>, ["~> 0.9.9.4"])
    end
  else
    s.add_dependency(%q<rack>, ["= 1.3.3"])
    s.add_dependency(%q<yajl-ruby>, [">= 0"])
    s.add_dependency(%q<faraday>, ["~> 0.7.5"])
    s.add_dependency(%q<nokogiri>, ["~> 1.5.0"])
    s.add_dependency(%q<eventmachine>, ["~> 1.0.3"])
    s.add_dependency(%q<scamp>, [">= 0"])
    s.add_dependency(%q<can-has-lolcat>, [">= 0"])
    s.add_dependency(%q<papertrail-cli>, ["~> 0.8.5"])
    s.add_dependency(%q<hpricot>, ["~> 0.8.5"])
    s.add_dependency(%q<redis>, ["~> 2.2.2"])
    s.add_dependency(%q<hiredis>, ["~> 0.4.5"])
    s.add_dependency(%q<em-synchrony>, [">= 0"])
    s.add_dependency(%q<rollout>, ["~> 2.0.0"])
    s.add_dependency(%q<rollout-zk>, ["~> 1.0.1"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<pry>, ["~> 0.9.9.4"])
  end
end

